# Generated by Django 2.1.2 on 2018-10-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_A', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BettingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_for', models.BooleanField()),
                ('gotw_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_A', models.CharField(max_length=200)),
                ('team_B', models.CharField(max_length=200)),
                ('team_A_is_favorite', models.BooleanField()),
                ('team_B_is_favorite', models.BooleanField()),
                ('tv_channel', models.CharField(max_length=200)),
                ('game_time', models.DateTimeField()),
                ('line', models.DecimalField(decimal_places=1, max_digits=5)),
                ('team_A_score', models.PositiveIntegerField()),
                ('team_B_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('is_winston_cup_participant', models.BooleanField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.PositiveIntegerField()),
                ('game_of_such', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_of_week', to='betcha_app.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcha_app.Week'),
        ),
        migrations.AddField(
            model_name='bettingsheet',
            name='better',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcha_app.User'),
        ),
        migrations.AddField(
            model_name='bettingsheet',
            name='high_risk_bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betcha_app.Bet'),
        ),
        migrations.AddField(
            model_name='bettingsheet',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcha_app.Week'),
        ),
        migrations.AddField(
            model_name='bet',
            name='betting_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcha_app.BettingSheet'),
        ),
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcha_app.Game'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcha_app.User'),
        ),
    ]
