# Generated by Django 2.1.2 on 2018-10-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betcha_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team_B_is_favorite',
            new_name='team_A_is_home',
        ),
    ]
