# Generated by Django 2.1.2 on 2018-10-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betcha_app', '0002_auto_20181016_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='game_of_such',
        ),
    ]
