# Generated by Django 2.1.2 on 2018-10-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betcha_app', '0003_remove_week_game_of_such'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='game_of_such',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_of_week', to='betcha_app.Game'),
        ),
    ]
